# Generated by Django 2.2.8 on 2020-12-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='初期ユーザー', max_length=50, verbose_name='nickname'),
        ),
    ]
