# Generated by Django 2.2.8 on 2020-12-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201215_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='static/blogimage.png', upload_to='media/blog/%Y/%m/%d', verbose_name='サムネイル'),
        ),
    ]
