# Generated by Django 2.2.8 on 2020-12-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
