# Generated by Django 2.2.8 on 2020-12-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='タイトル'),
            preserve_default=False,
        ),
    ]
