# Generated by Django 2.2.8 on 2020-12-15 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_image', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='サムネイル')),
                ('theme', models.TextField(verbose_name='テーマ')),
                ('pencase', models.TextField(verbose_name='筆箱')),
                ('mechanical_pencil', models.TextField(verbose_name='シャーペン')),
                ('ball_point_pen', models.TextField(verbose_name='ボールペン')),
                ('eraser', models.TextField(verbose_name='消しゴム')),
                ('others', models.TextField(verbose_name='その他')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='article_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('comment_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pencaseapp.Article')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pencaseapp.Comment')),
                ('replyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
