# Generated by Django 2.2.8 on 2020-12-16 02:18

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pencaseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media/%Y/%m/%d'),
        ),
    ]
