# Generated by Django 2.2.8 on 2020-12-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pencaseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='origin_image',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='サムネイル'),
        ),
    ]
