# Generated by Django 2.2.8 on 2020-12-12 05:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pencaseapp', '0002_auto_20201210_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='article',
            name='origin_image',
            field=models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=20, verbose_name='タイトル'),
        ),
    ]
