# Generated by Django 2.2.8 on 2020-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pencaseapp', '0003_auto_20201212_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='ball_point_pen',
            field=models.TextField(default='説明なし', verbose_name='ボールペン'),
        ),
        migrations.AddField(
            model_name='article',
            name='eraser',
            field=models.TextField(default='説明なし', verbose_name='消しゴム'),
        ),
        migrations.AddField(
            model_name='article',
            name='mechanical_pencil',
            field=models.TextField(default='説明なし', verbose_name='シャーペン'),
        ),
        migrations.AddField(
            model_name='article',
            name='others',
            field=models.TextField(default='説明なし', verbose_name='その他'),
        ),
        migrations.AddField(
            model_name='article',
            name='pencase',
            field=models.TextField(default='説明なし', verbose_name='筆箱'),
        ),
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.CharField(default='なし', max_length=20, verbose_name='テーマ'),
        ),
    ]
