# Generated by Django 2.2.8 on 2020-12-12 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pencaseapp', '0004_auto_20201212_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ball_point_pen',
            field=models.TextField(verbose_name='ボールペン'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='eraser',
            field=models.TextField(verbose_name='消しゴム'),
        ),
        migrations.AlterField(
            model_name='article',
            name='mechanical_pencil',
            field=models.TextField(verbose_name='シャーペン'),
        ),
        migrations.AlterField(
            model_name='article',
            name='others',
            field=models.TextField(verbose_name='その他'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pencase',
            field=models.TextField(verbose_name='筆箱'),
        ),
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.CharField(max_length=50, verbose_name='テーマ'),
        ),
    ]
