# Generated by Django 2.2.8 on 2020-12-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pencaseapp', '0005_auto_20201212_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.TextField(verbose_name='テーマ'),
        ),
    ]
