# Generated by Django 2.2.8 on 2020-12-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pencaseapp', '0006_auto_20201212_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='text',
            new_name='reply_text',
        ),
    ]
